#!/local/bin/perl

=head1  NAME 

fuzznuc2bsml.pl - convert fuzznuc raw output to BSML

=head1 SYNOPSIS

USAGE: fuzznuc2bsml.pl 
        --input=/path/to/somefile.hmmpfam.raw 
        --output=/path/to/somefile.hmmpfam.bsml
        --fasta_input=/path/to/hmmpfam/input.fsa
        --gzip_output=1
        --log=/path/to/some.log
        --debug=4 
        --help
      ]

=head1 OPTIONS

B<--input,-i> 
    Input raw alignment file from an hmmpfam search.

B<--output,-o> 
    Output BSML file

B<--fasta_input,-f>
    Optional.  If included, will make a seq data import element and include the 
    defline with the sequences.

B<--gzip_output,-g>
    Optional.  If given a non-zero value, will compress the output and give the output
    file a .gz extension.  If the file already contains one, it won't add another.

B<--debug,-d> 
    Debug level.  Use a large number to turn on verbose debugging. 

B<--log,-l> 
    Log file

B<--help,-h> 
    This help message

=head1   DESCRIPTION

This script is used to convert the raw alignment output from an hmmpfam search into BSML.

=head1 INPUT

The input file passed to this script must be a raw alignment file generated by hmmpfam.
Define the input file using the --input option.

Illegal characters will be removed from the IDs for the query sequence and subject hit
if necessary to create legal XML id names.  For each element, the original, unmodified 
name will be stored in the "title" attribute of the Sequence element.  You should make 
sure that your ids don't begin with a number.  This script will successfully create a 
BSML document regardless of your ID names, but the resulting document may not pass DTD 
validation.

=head1 OUTPUT

The BSML file to be created is defined using the --output option.  If the file already exists
it will be overwritten.

Because the hmmpfam executable is used to perform a variety of searches, including hmmsmart
and hmmtigr, the user may pass a value using --search_method, which will create the
appropriate titles in the BSML Analysis element.  If not passed, the default 'hmmpfam' is used.

=head1 CONTACT

    Joshua Orvis
    jorvis@tigr.org

=cut

use strict;
use Getopt::Long qw(:config no_ignore_case no_auto_abbrev);
use Pod::Usage;
use Ergatis::Logger;
use BSML::BsmlRepository;
use BSML::BsmlBuilder;
use BSML::BsmlParserTwig;

my $fasta_input;

my %options = ();
my $results = GetOptions (\%options, 
              'input|i=s',
              'output|o=s',
              'fasta_input|f=s',
              'gzip_output|g=s',
              'log|l=s',
              'debug=s',
              'help|h') || pod2usage();

my $logfile = $options{'log'} || Ergatis::Logger::get_default_logfilename();
my $logger = new Ergatis::Logger('LOG_FILE'=>$logfile,
                  'LOG_LEVEL'=>$options{'debug'});
$logger = $logger->get_logger();

# display documentation
if( $options{'help'} ){
    pod2usage( {-exitval=>0, -verbose => 2, -output => \*STDOUT} );
}

## make sure all passed options are peachy
&check_parameters(\%options);

## we want a new doc
my $doc = new BSML::BsmlBuilder();

## open the input file for parsing
open (my $ifh, $options{'input'}) || $logger->logdie("can't open input file for reading");

## go through the top of the file and get a few things.
my ($pattern, $pattern_name,$seq_file,$pat_seq);
while (<$ifh>) {
    if (/-pattern\s+(\S+)/) {
        $pat_seq = $1;
    } elsif (/pname\s+(\S+)/) {
        $pattern_name = $1;
	  }elsif (/-sequence\s+(\S+)/) {
          $seq_file = $1;
	  }
    elsif(/Report_file/) {
        last;
    }
}

my $pattern = $doc->createAndAddSequence($pattern_name, $pattern_name, undef, 'na', 'DNA');
$doc->createAndAddSeqData($pattern_name,$pat_seq);
## fetch deflines
#my $deflines = get_deflines($sequence_file);

## check that these were successfully parsed
unless ($pattern_name)      { $logger->logdie("HMM file definition not found in input file.") }
unless ($seq_file) { $logger->logdie("Sequence file definition not found in input file.") }

#my $hmm_name = $hmm_file;
#$hmm_name =~ s/.*\///;
#$nmm_name =~ s/\..*//;
my($seq_name,$start,$end,$score,$strand,$pattern, $seq, %alignments);

while (<$ifh>) {
  #Feature: 1
		  #Name: ntnm01.assembly.81.0
		  #Start: 9340
		  #End: 9359
		  #Length: 20
		  #Score: 20
		  #Strand: +
		  #Pattern_name: dRS3_repeat
		  #Mismatch: .

		  if(/Name:\s(\S+)/) {
			$seq_name=$1;
		  }
		  elsif(/Start:\s(\S+)/) {
			$start=$1;
		  }
		  elsif(/End:\s(\S+)/) {
			$end = $1;
		  }
		  elsif(/Strand:\s(\S+)/) {
			$strand=$1;
		  }
		  elsif(/Score:\s(\S+)/) {
			$score=$1;
		  }
		  elsif(/Pattern_name:\s(\S+)/) {
#			$pattern=$1;
			## add this model sequence if we haven't already
			if( !( $doc->returnBsmlSequenceByIDR($seq_name)) ){
                $seq = $doc->createAndAddSequence($seq_name, $seq_name, undef, 'na', 'DNA');
			}
            
            if(!$alignments{$pattern_name}) {
                $alignments{$pattern_name} = $doc->createAndAddSequencePairAlignment( 
                                                                                      refseq => $seq_name,
                                                                                      #refstart => 0,
                                                                                      #refend => $cols[2] - 1,
                                                                                      #reflength => $cols[2],
                                                                                      compseq => $pattern_name,
                                                                                      class => 'match'
                                                                                      );
            }

                ## add a link element inside this seq-pair-alignment
                $alignments{$pattern_name}->addBsmlLink('analysis', "\#$options{search_method}_analysis", 'computed_by');
        
                ## add the total_score and total_eval for this pair
#                $doc->createAndAddBsmlAttribute($alignments{$pattern_name}, 'total_score', $score);
        
			my $linectr=0;
          my $run = $doc->createAndAddSequencePairRun(   
                                                         alignment_pair => $alignments{$pattern_name},
                                                         runscore => $score,
                                                         runlength => abs($start - $end) + 1,
                                                         comprunlength => abs($start - $end) + 1,
                                                         refpos => min($start, $end) - 1,
                                                         refcomplement => 0,
                                                         comppos => 0,
                                                         compcomplement => 0,
                                                         );
          ## add other attributes of the run
            $doc->createAndAddBsmlAttribute( $run, 'class', 'match_part');
        }
      }

## add the analysis element
$doc->createAndAddAnalysis(
                            id => "$options{search_method}_analysis",
                            sourcename => $options{'output'},
                            program => 'fuzznuc',
                            algorithm => 'fuzznuc',
                            version => 'na',
                          );

## now write the doc
$doc->write($options{'output'}, '', $options{gzip_output});

exit;


sub check_parameters {
    
    ## make sure input file exists
    if (! -e $options{'input'}) { $logger->logdie("input file $options{'input'} does not exist") }

    ## make user an output file was passed
    if (! $options{'output'}) { $logger->logdie("output option required!") }

    ## handle defaults
    $options{'search_method'} = 'fuzznuc' unless ( $options{'search_method'} );

    if($options{'fasta_input'}) {
        $fasta_input = $options{'fasta_input'};
    }

    return 1;
}

sub min {
    my ($num1, $num2) = @_;
    
    if ($num1 < $num2) {
        return $num1;
    } else {
        return $num2;
    }
}

## retrieve deflines from a fasta file
sub get_deflines {
    my ($fasta_file) = @_;

    my $deflines = {};

    my $ifh;

    if (! -e $fasta_file) {
        if (-e $fasta_file.".gz") {
            $fasta_file .= ".gz";
        } elsif (-e $fasta_file.".gzip") {
            $fasta_file .= ".gzip";
        }
    }

    if ($fasta_file =~ /\.(gz|gzip)$/) {
        open ($ifh, "<:gzip", $fasta_file)
          || $logger->logdie("can't open input file '$fasta_file': $!");
    } else {
        open ($ifh, $fasta_file)
          || $logger->logdie("Failed opening '$fasta_file' for reading: $!");
      }

    while (<$ifh>) {
        unless (/^>/) {
            next;
        }
        chomp;
        if (/^>((\S+).*)$/) {
            $deflines->{$2} = $1;
        }
    }
    close $ifh;

    if (scalar(keys(%{$deflines})) < 1) {
        $logger->logwarn("defline lookup failed for '$fasta_file'");
    }

    return $deflines;
}
