#!/bin/sh
if [ -z "$SCHEMA_DOCS_DIR" ]
then
    SCHEMA_DOCS_DIR=
export SCHEMA_DOCS_DIR
fi
if [ -z "$WORKFLOW_WRAPPERS_DIR" ]
then
    WORKFLOW_WRAPPERS_DIR=/opt/ergatis/bin
export WORKFLOW_WRAPPERS_DIR
fi
if [ -z "$WORKFLOW_DOCS_DIR" ]
then
    WORKFLOW_DOCS_DIR=
export WORKFLOW_DOCS_DIR
fi

umask 0000
unset LD_LIBRARY_PATH

LANG=C
export LANG
LC_ALL=C
export LC_ALL

# Actual script code starts here

while [[ $# -ge 1 ]]
do
i="$1"
arg=$(echo $i | cut -f1 -d "=")
val=$(echo $i | cut -f2 -d "=")

case $arg in
	--first)
	first="$val"
    ;;
    --second)
    second="$val"
    ;;
    --paired)
    paired="$val"
    ;;
    --output_dir)
    out_dir="$val"
    ;;
    --spades_bin)
    spades_bin="$val"
    ;;
esac
shift 
done
cmd="${spades_bin}/spades.py --careful -o $out_dir"
if [ $paired ]
then
	cmd="$cmd -1 $first -2 $second"
else
	cmd="$cmd -s $first"
fi  
echo "$cmd"
$cmd

