#!/bin/sh
if [ -z "$SCHEMA_DOCS_DIR" ]
then
    SCHEMA_DOCS_DIR=
export SCHEMA_DOCS_DIR
fi
if [ -z "$WORKFLOW_WRAPPERS_DIR" ]
then
    WORKFLOW_WRAPPERS_DIR=/opt/ergatis/bin
export WORKFLOW_WRAPPERS_DIR
fi
if [ -z "$WORKFLOW_DOCS_DIR" ]
then
    WORKFLOW_DOCS_DIR=
export WORKFLOW_DOCS_DIR
fi

umask 0000
unset LD_LIBRARY_PATH

LANG=C
export LANG
LC_ALL=C
export LC_ALL

# Actual script code starts here

while [[ $# -ge 1 ]]
do
i="$1"
arg=$(echo $i | cut -f1 -d "=")
val=$(echo $i | cut -f2 -d "=")

case $arg in
	--input_list)
	input="$val"
    ;;
    --output_dir)
    out_dir="$val"
    ;;
    --spades_bin)
    spades_bin="$val"
    ;;
esac
shift 
done

if [ ! -d "$spades_bin" ]; then
	echo "Cannot find SPAdes directory at $spades_bin: Exiting" >&2
	exit 1
fi

cmd="${spades_bin}/spades.py --careful -o $out_dir"

line_count=$(wc -l $input | cut -f1 -d' ')
if [ $line_count -eq 2 ]; then
	first=`head -n 1 $input`
	second=`tail -n 1 $input`
	cmd="$cmd -1 $first -2 $second"
elif [ $line_count -eq 1 ]; then
	cmd="$cmd -s $first"
else
    echo "FASTQ list must have exactly 1 or 2 sequences.  This file had $line_count" >&2
    exit 1
fi

echo "$cmd"
$cmd

exit 0
