#!/bin/sh
if [ -z "$SCHEMA_DOCS_DIR" ]
then
    SCHEMA_DOCS_DIR=
export SCHEMA_DOCS_DIR
fi
if [ -z "$WORKFLOW_WRAPPERS_DIR" ]
then
    WORKFLOW_WRAPPERS_DIR=/opt/ergatis/bin
export WORKFLOW_WRAPPERS_DIR
fi
if [ -z "$WORKFLOW_DOCS_DIR" ]
then
    WORKFLOW_DOCS_DIR=
export WORKFLOW_DOCS_DIR
fi

umask 0000
unset LD_LIBRARY_PATH

LANG=C
export LANG
LC_ALL=C
export LC_ALL

source /opt/opt-packages/qiime-1.8/activate.sh

while [[ $# -ge 1 ]]
do
i="$1"
arg=$(echo $i | cut -f1 -d "=" )
val=$(echo $i | cut -f2 -d "=" )
case $i in
    -q)
    qual="$val"
    ;;
    -m)
    mapf="$val"
    ;;
    -f)
    fasta="$val"
    ;;
    -o)
    out="$val"
    ;;
    -b)
    barcode="$val"
    ;;
    -l)
    min="$val"
    ;;
    -L)
    max="$val"
    ;;
    -H)
    homo="$val"
    ;;
    -a)
    ambig="$val"
    ;;
esac
shift 
done
cmd="split_libraries.py -m $mapf -f $fasta -o $out -b $barcode -l $min -L $max -H $homo -a $ambig"
if [ -s $qual ]
then
     cmd="$cmd -q $qual"
fi  
$cmd

